### ISSUE TITLE
PID Number not showing

### ISSUE THREAD

**Issue by Kmrfarmsinc** [geezacoleman/OpenWeedLocator#102]
Using the quick method, I am finding it easy to navigate through the steps until I get to the step where it asks you to find out and stop the program using the PID number. My second row doesn't show up. You list some solutions that may work for others but I am just not sure how to go about this. I followed the previous steps exactly and have erased and started over many times over. I have the same problem every time, would you be able to assist?

**Comment by geezacoleman** [comment]
Thanks for persisting with the setup and trying it a few times. I have a few questions just to clarify what's happening a little more. Are you at the [Legacy Focusing](https://github.com/geezacoleman/OpenWeedLocator#legacy-focusing) step? If you successfully run the update owl step in [Step 4,](https://github.com/geezacoleman/OpenWeedLocator#legacy-focusing) you shouldn't need to do this. The focus_owl.sh file will do this all for you now. So this Legacy Focusing step isn't required.

But just in case - do you get errors if you run `owl.py` that may suggest the camera is running in the background?

Can you share the outputs/commands you are running in the lead up to this?

The second row will only likely show up if the program you specify (i.e. owl.py) is running - so if it isn't showing up, it could be due to owl.py being misspelled when you type or perhaps greenonbrown.py running instead, or otherwise it might not be running at all anyway so nothing to worry about.

Let me know how you go - happy to answer any more questions you might have.

**Comment by geezacoleman** [comment]
Ok thanks for the update.

'blessed' is a Python library and it looks like it hasn't been installed into the ´owl´ virtual environment. Did you run 

```
pi@raspberrypi:~/owl $ workon owl
(owl) pi@raspberrypi:~/owl $ pip install -r requirements.txt 
```

You can also try just `pip install blessed`, just make sure you are in the `owl` virtual environment first by typing `workon owl`.

**Comment by geezacoleman** [comment]
Great! Glad to hear you could get it running.

Yeh, we set it up for outdoors use in Australia, so all the settings are meant for those bright conditions, which means it's very dark inside. So good point on the focusing for indoor conditions - I might need to change it so you can specify indoor/outdoor when focusing or make the exposure mode auto.

To run it without the blurriness value (i.e. as normal), if you just want to see the feed, you can run:

`./owl.py --show-display --exp-mode 'auto'`

If you want to run ´focus_owl.sh´, you'll need to open it in a text editor and then edit the last line by adding the `--exp-mode 'auto'` flag too. 

I'll update this in the repository for others to use too!

**Comment by geezacoleman** [comment]
It seems this issue is resolved, so I'll close this one but feel free to add anything else that comes up or start a new issue if you come across any further issues.
